### ISSUE TITLE
Integrate the project into CI , like Travis

### ISSUE THREAD

**Issue by hosszubalazs** [kukko/web-wombat#5]
A continuous integration tool, like Travis CI should be integrated in the project. The effort is probably:
- some clicks on Travis CI site to link it to your github account
- commit a Travis Ci config file. This guide should help creating a minimal build script: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

Benefits : 
- it should help future contribution by checking PR builds. Not sure the exact functionality of Travis, but pull-requests should be tested before merge, and I think Travis is happy to do that.
- The automated build config acts as a minimal documentation on how to build and test the project.
- You can add a nice badge to the README, sends a positive message to passer-bys. :)

**Comment by kukko** [comment]
Thanks for the recomendation. I already created some test, a test runner and a pre-commit hook on my local machine which runs the tests and prevent the commit if some of the fails.

Now I will integrate the project with Travis CI, because it is really simple, just two of the tests fails because WombatServer can't listen on 443 port. But I'm working on it.

**Comment by kukko** [comment]
I had successfully integrate the repository with Travis CI, so from now all commits and theoretically all pull requests will be tested autmatically. I just needed to ignore two tests, because locally these can listen to 443 port, but at Travis's environment it's cannot. But I will solve it out as soon as possible.
